version: "3.9"
services:
  db:
    image: postgres:16
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: basetie
    volumes:
      - pgdata:/var/lib/postgresql/data
    ports:
      - "55432:5432"

  api:
    image: ${IMAGE:-todari/basetie-api}:${TAG:-latest}
    depends_on:
      - db
    environment:
      PORT: 8090
      DATABASE_URL: postgres://postgres:postgres@db:5432/basetie?sslmode=disable
      JWT_SECRET: ${JWT_SECRET}
      GOOGLE_CLIENT_ID: ${GOOGLE_CLIENT_ID}
      APPLE_BUNDLE_ID: ${APPLE_BUNDLE_ID}
      KBO_SYNC_ENABLED: ${KBO_SYNC_ENABLED:-false}
      KBO_SYNC_EVERY_HOURS: ${KBO_SYNC_EVERY_HOURS:-12}
      KBO_SYNC_SEASON: ${KBO_SYNC_SEASON:-}
      KBO_SYNC_MONTHS_AHEAD: ${KBO_SYNC_MONTHS_AHEAD:-0}
    ports:
      - "8090:8090"

volumes:
  pgdata:


